ON_Parasol:
  cell_type: ON_Parasol
  max_firing_rate: 700
  spatial:
    width: 35
    height: 35
    center_size: !expr 300/30
    surround_size: !expr 2*300/30
    center_strength: 1
    surround_strength: -0.5
  temporal:
    memory_ms: 250
    amp1: 0.6
    amp2: 0.3
    peak1_ms: 35
    peak2_ms: 55
    width1_ms: 21
    width2_ms: 38
  tiling_config:
    n_cells: None 
    rf_diameter: 35
    base_spacing: 6.0 
    offset: [0, 0]
    coverage_factor: 1.0
    selection_method: center_first
  nonlinearity:
    alpha: 1
    beta: 2
    gamma: 0
    type: soft-rectifier
OFF_Parasol:
  cell_type: OFF_Parasol
  max_firing_rate: 700
  spatial:
    width: 35
    height: 35
    center_size: !expr 250/30
    surround_size: !expr 2*250/30
    center_strength: 1.0 
    surround_strength: -0.5
  temporal:
    memory_ms: 250
    amp1: 0.5
    amp2: 0.15
    peak1_ms: 20
    peak2_ms: 70
    width1_ms: 25
    width2_ms: 50
  tiling_config:
    n_cells: None 
    rf_diameter: 35
    base_spacing: 6.0 
    offset: [0, 0]
    coverage_factor: 1.0
    selection_method: center_first
  nonlinearity:
    alpha: 1
    beta: 2
    gamma: 0
    type: soft-rectifier
ON_Midget:
  cell_type: ON_Midget
  max_firing_rate: 700
  spatial:
    width: 35
    height: 35
    center_size: !expr 125/30
    surround_size: !expr 2*125/30
    center_strength: 1.0 
    surround_strength: -0.5
  temporal:
    memory_ms: 250
    amp1: 0.5
    amp2: 0.15
    peak1_ms: 30
    peak2_ms: 70
    width1_ms: 20
    width2_ms: 50
  tiling_config:
    n_cells: None 
    rf_diameter: 35
    base_spacing: 6.0 
    offset: [0, 0]
    coverage_factor: 1.0
    selection_method: center_first
  nonlinearity:
    alpha: 1
    beta: 1
    gamma: 0
    type: soft-rectifier
OFF_Midget:
  cell_type: OFF_Midget
  max_firing_rate: 700
  spatial:
    width: 35
    height: 35
    center_size: !expr 100/30
    surround_size: !expr 2*100/30
    center_strength: 1.0 
    surround_strength: -0.5
  temporal:
    memory_ms: 250
    amp1: 0.5
    amp2: 0.05
    peak1_ms: 30
    peak2_ms: 100
    width1_ms: 25
    width2_ms: 50
  tiling_config:
    n_cells: None 
    rf_diameter: 35
    base_spacing: 6.0 
    offset: [0, 0]
    coverage_factor: 1.0
    selection_method: center_first
  nonlinearity:
    alpha: 1
    beta: 1
    gamma: 0
    type: soft-rectifier

video_parameters:
  frame_shape: [64, 64]
  frame_rate: 30